app:
  name: GoBaseProject
  env: development
  port: 8080

database:
  host: 120.53.251.75
  port: 13307
  name: go_base_project
  user: root
  password: change-me
  charset: utf8mb4

redis:
  host: 120.53.251.75
  port: 16379
  password: change-me
  db: 0

jwt:
  secret: change-me-in-production
  access_token_ttl_minutes: 120
  refresh_token_ttl_minutes: 10080
